// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EM.Core.Models.Entities;

[Table("Company")]
public partial class Company
{
    [Key]
    public int CompanyId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string CompanyName { get; set; }

    [StringLength(128)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ManagerId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string ManagerName { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string ManagerMobile { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string ManagerOfficialEmail { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string HRId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string HRName { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string HRMobile { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string HROfficialEmail { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LeadId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string LeadName { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string LeadMobile { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string LeadOfficialEmail { get; set; }

    public byte[] CompanyLogo { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string CompanyAddress { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string CompanyOfficialEmail { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CompanyOfficialContact { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string CompanyWebsite { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string CompanyFounder { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string CompanyFoundedMonthYear { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string CompanyEmployeeStrength { get; set; }

    [InverseProperty("Company")]
    public virtual ICollection<CompanyDocumentConfigurableValue> CompanyDocumentConfigurableValues { get; set; } = new List<CompanyDocumentConfigurableValue>();

    [InverseProperty("Company")]
    public virtual ICollection<CompanyDocument> CompanyDocuments { get; set; } = new List<CompanyDocument>();

    [ForeignKey("CreatedBy")]
    [InverseProperty("Companies")]
    public virtual AspNetUser CreatedByNavigation { get; set; }

    [InverseProperty("Company")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}