// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EM.Core.Models.Entities;

public partial class CompanyDocumentConfigurableValue
{
    [Key]
    public int Id { get; set; }

    public int? CompanyId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string FieldName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ValueType { get; set; }

    [StringLength(5000)]
    [Unicode(false)]
    public string FieldValue { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AddedDate { get; set; }

    public int? CompanyDocumentId { get; set; }

    [StringLength(2000)]
    [Unicode(false)]
    public string FieldFormat { get; set; }

    [ForeignKey("CompanyId")]
    [InverseProperty("CompanyDocumentConfigurableValues")]
    public virtual Company Company { get; set; }

    [ForeignKey("CompanyDocumentId")]
    [InverseProperty("CompanyDocumentConfigurableValues")]
    public virtual CompanyDocument CompanyDocument { get; set; }
}