// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EM.Core.Models.Entities;

[Table("CompanyDocumentsType")]
public partial class CompanyDocumentsType
{
    [Key]
    public int DocumentTypeId { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string DocumentTypeName { get; set; }

    [InverseProperty("CompanyDocumentsType")]
    public virtual ICollection<CompanyDocument> CompanyDocuments { get; set; } = new List<CompanyDocument>();
}