// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EM.Core.Models.Entities;

public partial class CompanyDocument
{
    [Key]
    public int Id { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string DocumentName { get; set; }

    public byte[] DocumentPath { get; set; }

    [StringLength(128)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    public int? CompanyId { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string DocumentType { get; set; }

    public int? CompanyDocumentsTypeId { get; set; }

    [ForeignKey("CompanyId")]
    [InverseProperty("CompanyDocuments")]
    public virtual Company Company { get; set; }

    [InverseProperty("CompanyDocument")]
    public virtual ICollection<CompanyDocumentConfigurableValue> CompanyDocumentConfigurableValues { get; set; } = new List<CompanyDocumentConfigurableValue>();

    [ForeignKey("CompanyDocumentsTypeId")]
    [InverseProperty("CompanyDocuments")]
    public virtual CompanyDocumentsType CompanyDocumentsType { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("CompanyDocuments")]
    public virtual AspNetUser CreatedByNavigation { get; set; }
}