// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EM.Core.Models.Entities;

[Table("EmployeeIncrement")]
public partial class EmployeeIncrement
{
    [Key]
    public int Id { get; set; }

    [StringLength(128)]
    public string UserId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string HikeMonthYear { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? HikeInPercentage { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? HikeAmount { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? SalaryAfterHike { get; set; }

    public DateOnly? SalaryEffectiveFrom { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ModifiedDate { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("EmployeeIncrements")]
    public virtual AspNetUser User { get; set; }
}