// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EM.Core.Models.Entities;

[Table("Employee")]
[Index("Mobile", Name = "UQ__Employee__6FAE07827E70FAF8", IsUnique = true)]
[Index("EmailId", Name = "UQ__Employee__7ED91ACE36777FD4", IsUnique = true)]
[Index("PAN", Name = "UQ__Employee__C577943D1D751E58", IsUnique = true)]
public partial class Employee
{
    [Key]
    public int Id { get; set; }

    [StringLength(128)]
    public string UserId { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string FullName { get; set; }

    public byte[] Photo { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string PermanentAddress { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string CurrentAddress { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string PAN { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Mobile { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string AlternateMobile { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string EmailId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string AlternateEmailId { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string BloodGroup { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string HighestQualification { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string HighestQualificationPassoutMonthYear { get; set; }

    [StringLength(2000)]
    [Unicode(false)]
    public string Technology { get; set; }

    public DateOnly? OfferDate { get; set; }

    public DateOnly? JoiningDate { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string OfferDesignation { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string CurrentDesignation { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? OfferSalary { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? CurrentSalary { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string LastHikeMonthYear { get; set; }

    public DateOnly? ResignationDate { get; set; }

    public DateOnly? RelivingDate { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string OfficialEmployeeId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string OfficialEmailId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string OfficialEmailIdPassword { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AddedDate { get; set; }

    public int? CompanyId { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Gender { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Adhaar { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string UAN { get; set; }

    [ForeignKey("CompanyId")]
    [InverseProperty("Employees")]
    public virtual Company Company { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Employees")]
    public virtual AspNetUser User { get; set; }
}