// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EM.Core.Models.Entities;

[Table("EmployeeITExperience")]
public partial class EmployeeITExperience
{
    [Key]
    public int ExperienceId { get; set; }

    [StringLength(128)]
    public string UserId { get; set; }

    public int? BatchId { get; set; }

    public int? TeamId { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string ProjectName { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string ProjectTechnologies { get; set; }

    [StringLength(8000)]
    [Unicode(false)]
    public string ProjectDescription { get; set; }

    public DateTime? JoiningDate { get; set; }

    [Column(TypeName = "numeric(16, 2)")]
    public decimal? JoiningSalary { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string JoiningDesignation { get; set; }

    [Column(TypeName = "numeric(16, 2)")]
    public decimal? CurrentSalary { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string CurrentDesignation { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public DateTime? DeletedDate { get; set; }

    public int? BankAccountId { get; set; }

    [ForeignKey("BankAccountId")]
    [InverseProperty("EmployeeITExperiences")]
    public virtual EmployeeBankAccount BankAccount { get; set; }

    [ForeignKey("BatchId")]
    [InverseProperty("EmployeeITExperiences")]
    public virtual Batch Batch { get; set; }

    [ForeignKey("TeamId")]
    [InverseProperty("EmployeeITExperiences")]
    public virtual Team Team { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("EmployeeITExperiences")]
    public virtual AspNetUser User { get; set; }
}