// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EM.Core.Models.Entities;

[Table("EmployeeBankAccount")]
public partial class EmployeeBankAccount
{
    [Key]
    public int AccountId { get; set; }

    [StringLength(128)]
    public string UserId { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string BankName { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string BranchName { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string AccountNumber { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string IFSCCode { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public DateTime? DeletedDate { get; set; }

    [InverseProperty("Account")]
    public virtual ICollection<EmployeeExperiece> EmployeeExperieces { get; set; } = new List<EmployeeExperiece>();

    [InverseProperty("BankAccount")]
    public virtual ICollection<EmployeeITExperience> EmployeeITExperiences { get; set; } = new List<EmployeeITExperience>();
}