// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EM.Core.Models.Entities;

[Table("EmployeeExperiece")]
public partial class EmployeeExperiece
{
    [Key]
    public int ExperienceId { get; set; }

    [StringLength(128)]
    public string UserId { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string CompanyName { get; set; }

    public DateTime? JoiningDate { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? CurrentCTC { get; set; }

    public DateTime? RelivingDate { get; set; }

    public bool? IsPFOpted { get; set; }

    public bool? IsAllDocumentsAvailable { get; set; }

    public int? AccountId { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public DateTime? DeletedDate { get; set; }

    [ForeignKey("AccountId")]
    [InverseProperty("EmployeeExperieces")]
    public virtual EmployeeBankAccount Account { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("EmployeeExperieces")]
    public virtual AspNetUser User { get; set; }
}