// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EM.Core.Models.Entities;

[Table("EmployeeEducationType")]
public partial class EmployeeEducationType
{
    [Key]
    public int EducationTypeId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EducationName { get; set; }

    [InverseProperty("EducationType")]
    public virtual ICollection<EmployeeEducation> EmployeeEducations { get; set; } = new List<EmployeeEducation>();
}