// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EM.Core.Models.Entities;

[Table("EmployeeEducation")]
public partial class EmployeeEducation
{
    [Key]
    public int EducationId { get; set; }

    [StringLength(128)]
    public string UserId { get; set; }

    public int? EducationTypeId { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string CollegeName { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? Percentage { get; set; }

    public int? PassoutYear { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Specialization { get; set; }

    [ForeignKey("EducationTypeId")]
    [InverseProperty("EmployeeEducations")]
    public virtual EmployeeEducationType EducationType { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("EmployeeEducations")]
    public virtual AspNetUser User { get; set; }
}