// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EM.Core.Models.Entities;

public partial class EmployeeInterview
{
    [Key]
    public int Id { get; set; }

    [StringLength(128)]
    public string UserId { get; set; }

    [StringLength(2000)]
    [Unicode(false)]
    public string CompanyName { get; set; }

    public DateOnly? InterviewDate { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string InterviewerName { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string InterviewRound { get; set; }

    public string InterviewQuestions { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("EmployeeInterviews")]
    public virtual AspNetUser User { get; set; }
}