// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EM.Core.Models.Entities;

[Table("EmployeeResignation")]
public partial class EmployeeResignation
{
    [Key]
    public int Id { get; set; }

    [StringLength(128)]
    public string UserId { get; set; }

    [StringLength(2000)]
    [Unicode(false)]
    public string CompanyOffers { get; set; }

    public DateOnly? ResignationDate { get; set; }

    public DateOnly? LastWorkingDay { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("EmployeeResignations")]
    public virtual AspNetUser User { get; set; }
}