// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EM.Core.Models.Entities;

[Table("Team")]
public partial class Team
{
    [Key]
    public int TeamId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string TeamName { get; set; }

    [InverseProperty("Team")]
    public virtual ICollection<EmployeeITExperience> EmployeeITExperiences { get; set; } = new List<EmployeeITExperience>();
}